services:
  client:
    image: node:20
    volumes:
      - ./client:/home/node/app
    restart: always
    working_dir: /home/node/app
    depends_on:
      - server
    command:  /bin/sh -c 'npm install && npm run start:dev'
    env_file:
      - ./client/.env
    environment:
      - REACT_APP_BASE_URL=http://localhost:8085
    ports:
      - 3002:3002
  
  server:
    image: node:20
    volumes:
      - ./server:/home/node/app
    working_dir: /home/node/app
    env_file:
      - ./server/.env
    environment:
      - PORT=8085
    command: /bin/sh -c 'npm install && npm run start:dev'
    ports:
      - 8085:8085
